######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 19 17:33:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calender.h
SOURCES += main.cpp
