######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 17 22:48:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += table_widget.cpp
