######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 17 22:55:04 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pdf_writer.cpp
