######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 29 01:12:30 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stackdialog.h
SOURCES += main.cpp stackdialog.cpp
